export interface Infor {
    id: number;
    firstName: string;
    lastName: string;
    hook: null | string;
    companyName: string;
    email: string;
    phone: number;
    address: null | string;
    slogan: null | string;
    briefIntro: null | string;
    profilePicture: null | string;
    referralCode: any;
    role: any;
    stripeCustomerId: null | string;
    country: null | string;
    state: null | string;
    signatureURL: null | string;
    initialURL: null | string;
    status: string;
    subscriptionId: number;
    totalLeavesEarned: number;
    totalCreditsEarned: number;
    referreeId: null | number;
    timezone: null | string;
    isReferreePaid: any;
    isTutorialPassed: number;
    mainAccountId: null | number;
    numberOfReferrals: number;
    totalPages: number;
    businessPage: string;
    teamAccess: null | string;
    socialLogin: null | string;
    socialId: null | string;
    secret: null | string;
    isAdmin: number;
    isEmailVerified: number;
    allowCopy: number;
    teamId: number;
    createdAt: string;
    updatedAt: string;
    memberId: null | number;
}

export interface TabUser {
    address: string | null;
    allowCopy: number;
    briefIntro: string | null;
    businessPage: string;
    companyName: string;
    country: string | null;
    createdAt: string;
    email: string;
    firstName: string;
    hook: string | null;
    id: number;
    initialURL: string | null;
    isAdmin: number;
    isEmailVerified: number;
    isReferreePaid: number;
    isTutorialPassed: number;
    lastName: string;
    mainAccountId: string | null;
    memberId: string | null;
    numberOfReferrals: number;
    phone: string;
    profilePicture: string | null;
    referralCode: string;
    referreeId: string | null;
    role: string;
    secret: string | null;
    signatureURL: string | null;
    slogan: string | null;
    socialId: string | null;
    socialLogin: string | null;
    state: string | null;
    status: string;
    stripeCustomerId: string | null;
    subscriptionId: number;
    teamAccess: string | null;
    teamId: string;
    timezone: string | null;
    totalCreditsEarned: number;
    totalLeavesEarned: number;
    totalPages: number;
    updatedAt: string;
  }
  
