export interface Infor {
    id: number;
    firstName: string;
    lastName: string;
    hook: null | string;
    companyName: string;
    email: string;
    phone: number;
    address: null | string;
    slogan: null | string;
    briefIntro: null | string;
    profilePicture: null | string;
    referralCode: any;
    role: any;
    stripeCustomerId: null | string;
    country: null | string;
    state: null | string;
    signatureURL: null | string;
    initialURL: null | string;
    status: string;
    subscriptionId: number;
    totalLeavesEarned: number;
    totalCreditsEarned: number;
    referreeId: null | number;
    timezone: null | string;
    isReferreePaid: any;
    isTutorialPassed: number;
    mainAccountId: null | number;
    numberOfReferrals: number;
    totalPages: number;
    businessPage: string;
    teamAccess: null | string;
    socialLogin: null | string;
    socialId: null | string;
    secret: null | string;
    isAdmin: number;
    isEmailVerified: number;
    allowCopy: number;
    teamId: number;
    createdAt: string;
    updatedAt: string;
    memberId: null | number;
}
