export const BASE_URL = "https://dev-backend.paperlink.app";
export const accessToken =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6ImFjY2VzcyJ9.eyJpYXQiOjE2OTYxMTU3MDYsImV4cCI6MTY5NjIwMjEwNiwiYXVkIjoiaHR0cHM6Ly95b3VyZG9tYWluLmNvbSIsImlzcyI6ImZlYXRoZXJzIiwic3ViIjoiNiIsImp0aSI6ImYzM2M2NDU1LTg0MjgtNGJjYi1iMTJkLWMxOWU5NzNmMzQ0ZSJ9.onCSMJSjRb4yDNkF2sEfyS_4_7wddyqIdqavHA8o-40";
